version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: evPlug
    ports:
      - 443:443
    depends_on:
      - mongodb
    volumes:
      - ./:/app
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - ./home/mongodb:/home/mongodb
      - mongo-data:/data/db
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongodb:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo-data: